# Datasource configuration

spring:
  datasource:
    url: ${db.url:jdbc:mysql://localhost:3306/test-db}
    username: ${db,username:root}
    password: ${db.password:1234}

  flyway:
    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
