server.port: 8761

spring.application.name: eureka

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    leaseExpirationDurationInSeconds: 90
    lease-expiration-duration-in-seconds: 6000
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 90000
  client:
    register-with-eureka: false
    fetch-registry: false


logging:
  level:
    com.netflix.eureka: TRACE
    com.netflix.discovery: TRACE