apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-was-green
  namespace: ns-sample
spec:
  selector:
    matchLabels:
      pod-type: was
      blue-green-type: green
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        pod-type: was
        blue-green-type: green
    spec:
      subdomain: svc-db-router
      containers:
      - name: container
        image: progress0407/app-ver2
        envFrom:
        - configMapRef:
            name: cm-was
        resources:
          requests:
            memory: 20Mi
          limits:
            memory: 300Mi
        readinessProbe:
          httpGet:
            path: /hi
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 60
      terminationGracePeriodSeconds: 0