apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-blue
  namespace: ns-sample
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    pod-type: was
    blue-green-type: blue
