version: "3.8"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: chat-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chatdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ~/data/mongodb/data/db:/data/db
