apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-was
  namespace: ns-sample
spec:
  selector:
    matchLabels:
      pod-type: was
  replicas: 1
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        pod-type: was
    spec:
      subdomain: svc-db-router
      containers:
      - name: container
        image: progress0407/app
        envFrom:
        - configMapRef:
            name: cm-was
        resources:
          requests:
            memory: 20Mi
          limits:
            memory: 300Mi
        readinessProbe:
          httpGet:
            path: /hi
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 3
          timeoutSeconds: 100
      terminationGracePeriodSeconds: 0