version: '3.7'

services:
  db:
    container_name: db-container
    image: mysql:8.0.3
    environment:
      MYSQL_DATABASE: docker_app
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'

  app:
    container_name: app-container
    depends_on:
      - db
    image: progress0407/docker-app
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/docker_app?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
