version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    restart: always
    container_name: test-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test-db
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/data/mysql/data:/var/lib/mysql
