CREATE USER 'philo'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'philo'@'%' WITH GRANT OPTION;

CREATE USER 'philo'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'philo'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;
