server.port: 8081

spring:
  application.name: micro-service-1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 6000
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 600

#  management.endpoints.web.exposure.include=*
#  management.endpoint.shutdown.enabled=true


management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "info"
          - "busrefresh"
          - "bus-refresh"
          - "health"

