apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-spring-boot
spec:
  serviceName: nginx
  replicas: 1
  selector:
    matchLabels:
      pod-type: nginx
  template:
    metadata:
      labels:
        pod-type: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf
          configMap:
            name: cm-nginx
      terminationGracePeriodSeconds: 0
