apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
  namespace: ns-1nginx-1was
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    pod-type: nginx
