apiVersion: v1
kind: Service
metadata:
  name: svc-router
  namespace: ns-1nginx-1was
spec:
  clusterIP: None
  selector:
    pod-type: was
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080